<?php

return [
"A special PetrogisMobile application for Android mobile devices will be useful for working on rock art monuments. The application allows to quickly document panels with petroglyphs, their geographical coordinates and orientation in automatic mode. The application can work offline, and when access to the Internet appears, automatically uploads the collected data to the information system artemiris.org." => "Для работы на памятниках наскального искусства будет полезно специальное приложение PetrogisMobile для мобильных устройств под управлением Android. Приложение позволяет выполнять быструю фиксацию плоскостей с наскальными рисунками, их географических координат и ориентации в автоматическом режиме. Приложение может работать в автономном режиме, а при появлении доступа к сети Интернет – автоматически закачивать собранные данные в информационную систему artemiris.org.",
"The application allows to use data from the information system to navigate through monuments – to search and display on the map the desired panel, its location relative to the current position of the user." => "Приложение позволяет использовать данные информационной системы для навигации по памятникам – поиска и отображения на карте искомой плоскости, её местоположения относительно текущей позиции пользователя.",
"To install the application, it is needed to download the application file by the link and run its installation on the device. In the mobile device settings, it should be allowed to install applications from unknown sources." => "Для установки приложения необходимо скачать файл приложения по ссылке и запустить его установку на устройстве. В настройках мобильного устройства должна быть разрешена установка приложений из неизвестных источников.",
"To document a rock drawing or surface using a mobile application, the following actions should be performed in the specified order:" => "Для фиксации наскального рисунка или поверхности с использованием мобильного приложения необходимо проделать следующие действия в заданном порядке:",
"Press the “Photo” button, then using the opened object photographing interface, take a snapshot of the object. The mobile device in this case should be located as parallel as possible to the photographed plane. The orientation of the plane will be automatically set based on the orientation in the space of the mobile device." => "нажать кнопку «Фото», с помощью открывшегося интерфейса фотографирования объекта сделать снимок объекта. Мобильное устройство при этом должно быть расположено как можно более параллельно фотографируемой плоскости. Ориентация плоскости будет автоматически задана на основе ориентации в пространстве мобильного устройства.",
"Enter the name of the object into the corresponding field from the virtual keyboard or speech recognition system." => "Ввести с виртуальной клавиатуры или системы распознавания речи название объекта в соответствующее поле.",
"Ensure that the coordinates of the device location are displayed in the appropriate fields. If this does not happen - you need to wait, the cold start of GPS can take up to 5 minutes, but this usually happens only when you start the application for the first time in a new place." => "Убедиться, что в соответствующих полях отображаются координаты местоположения устройства. Если этого не происходит – необходимо подождать, холодный старт GPS может занять до 5 минут, но такое обычно происходит только при первом запуске приложения на новом месте.",
"Click the “Save” button to save data to the local device database." => "Нажать кнопку «Сохранить» для сохранения данных в локальную базу данных устройства",
"When access to the Internet appears, click the “Sync” button to synchronize the collected data with the information system artemiris.org." => "При появлении доступа к сети Интернет нажать кнопку «Синхронизовать» для синхронизации собранных данных с Информационной системой artemiris.org.",
"Download Mobile Application (APK file)" => "Скачать мобильное приложение (APK файл)",
"Mobile Application" => "Мобильное приложение",

];